#!/usr/bin/env bash
###############################################################################
# Ru.na — coturn + Cloudflare DNS-01 TLS installer  (Ubuntu/Debian)
#
# Run on the VPS as root:    sudo bash install.sh
#
# Fill in the five variables below ON THE SERVER COPY ONLY.
# Do NOT commit real values back to git.
###############################################################################
set -euo pipefail

# ─── EDIT THESE (server copy only) ───────────────────────────────────────────
CF_ZONE="vantageos.my.id"                        # your Cloudflare zone (root domain)
TURN_DOMAIN="turn.vantageos.my.id"               # DNS name for this TURN server
PUBLIC_IP="REPLACE_WITH_PUBLIC_IP"               # this VPS's public IPv4
TURN_SECRET="REPLACE_WITH_LONG_RANDOM_SECRET"    # HMAC secret; MUST equal the edge fn's TURN_SECRET
CF_API_TOKEN="REPLACE_WITH_CLOUDFLARE_TOKEN"     # Cloudflare token, scope: Zone › DNS › Edit (+ Zone Read)
LE_EMAIL="REPLACE_WITH_YOUR_EMAIL"               # Let's Encrypt expiry notices
# ─────────────────────────────────────────────────────────────────────────────
# Tip: generate the secret with:  openssl rand -hex 32
# Set the SAME value on Supabase:  supabase secrets set TURN_SECRET="<that value>"

[[ $EUID -eq 0 ]] || { echo "Run as root:  sudo bash install.sh"; exit 1; }
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "==> Installing coturn + certbot (Cloudflare DNS plugin)…"
apt-get update
apt-get install -y coturn certbot python3-certbot-dns-cloudflare curl python3

echo "==> Enabling coturn service flag…"
if grep -q '^#TURNSERVER_ENABLED=1' /etc/default/coturn 2>/dev/null; then
  sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
elif ! grep -q '^TURNSERVER_ENABLED=1' /etc/default/coturn 2>/dev/null; then
  echo 'TURNSERVER_ENABLED=1' >> /etc/default/coturn
fi

echo "==> Writing Cloudflare API credentials (root-only, 0600)…"
install -d -m 700 /root/.secrets
umask 077
cat > /root/.secrets/cloudflare.ini <<EOF
dns_cloudflare_api_token = ${CF_API_TOKEN}
EOF
chmod 600 /root/.secrets/cloudflare.ini

echo "==> Creating/updating the grey-cloud A record ${TURN_DOMAIN} -> ${PUBLIC_IP} via Cloudflare API…"
CF_API="https://api.cloudflare.com/client/v4"
cf_get() { curl -fsS -H "Authorization: Bearer ${CF_API_TOKEN}" "${CF_API}/$1"; }
# Resolve the zone id (token needs Zone:Read, included in the "Edit zone DNS" template).
ZONE_ID="$(cf_get "zones?name=${CF_ZONE}" | python3 -c \
  'import sys,json;r=json.load(sys.stdin).get("result") or [];print(r[0]["id"] if r else "")')"
if [[ -z "${ZONE_ID}" ]]; then
  echo "!! Could not resolve zone '${CF_ZONE}'. Check CF_ZONE and the token's Zone:Read scope." >&2
  exit 1
fi
# Does the record already exist?
REC_ID="$(cf_get "zones/${ZONE_ID}/dns_records?type=A&name=${TURN_DOMAIN}" | python3 -c \
  'import sys,json;r=json.load(sys.stdin).get("result") or [];print(r[0]["id"] if r else "")')"
# proxied=false  ==  grey cloud  (TURN's UDP/relay traffic can't go through Cloudflare's proxy)
REC_BODY="$(printf '{"type":"A","name":"%s","content":"%s","ttl":120,"proxied":false}' "${TURN_DOMAIN}" "${PUBLIC_IP}")"
if [[ -n "${REC_ID}" ]]; then
  echo "    record exists — updating (and forcing DNS-only)…"
  curl -fsS -X PUT -H "Authorization: Bearer ${CF_API_TOKEN}" -H "content-type: application/json" \
    "${CF_API}/zones/${ZONE_ID}/dns_records/${REC_ID}" --data "${REC_BODY}" >/dev/null
else
  echo "    record missing — creating…"
  curl -fsS -X POST -H "Authorization: Bearer ${CF_API_TOKEN}" -H "content-type: application/json" \
    "${CF_API}/zones/${ZONE_ID}/dns_records" --data "${REC_BODY}" >/dev/null
fi
echo "    DNS record set (DNS only / grey cloud)."

echo "==> Requesting Let's Encrypt cert for ${TURN_DOMAIN} via Cloudflare DNS-01…"
certbot certonly \
  --dns-cloudflare \
  --dns-cloudflare-credentials /root/.secrets/cloudflare.ini \
  --dns-cloudflare-propagation-seconds 30 \
  -d "${TURN_DOMAIN}" \
  --non-interactive --agree-tos -m "${LE_EMAIL}"

echo "==> Installing certbot deploy hook (copies certs for coturn, then restarts)…"
install -d /etc/letsencrypt/renewal-hooks/deploy
cat > /etc/letsencrypt/renewal-hooks/deploy/coturn.sh <<EOF
#!/usr/bin/env bash
# Auto-generated by Ru.na install.sh. coturn runs as 'turnserver' and cannot
# read root-only /etc/letsencrypt/live/*, so copy the cert+key to a readable
# location on every renewal, then restart coturn to pick them up.
set -euo pipefail
DEST=/etc/coturn/certs
install -d -o turnserver -g turnserver -m 750 "\$DEST"
install -o turnserver -g turnserver -m 640 \\
  /etc/letsencrypt/live/${TURN_DOMAIN}/fullchain.pem "\$DEST/fullchain.pem"
install -o turnserver -g turnserver -m 640 \\
  /etc/letsencrypt/live/${TURN_DOMAIN}/privkey.pem "\$DEST/privkey.pem"
systemctl restart coturn
EOF
chmod +x /etc/letsencrypt/renewal-hooks/deploy/coturn.sh

echo "==> Running deploy hook once (initial issuance does not auto-trigger it)…"
/etc/letsencrypt/renewal-hooks/deploy/coturn.sh

echo "==> Installing /etc/turnserver.conf with your values…"
cp "${SCRIPT_DIR}/turnserver.conf" /etc/turnserver.conf
sed -i "s|REPLACE_WITH_PUBLIC_IP|${PUBLIC_IP}|g" /etc/turnserver.conf
sed -i "s|REPLACE_WITH_LONG_RANDOM_SECRET|${TURN_SECRET}|g" /etc/turnserver.conf

echo "==> Opening firewall ports (ufw)…"
if command -v ufw >/dev/null 2>&1; then
  ufw allow 3478/tcp
  ufw allow 3478/udp
  ufw allow 5349/tcp
  ufw allow 5349/udp
  ufw allow 49152:49251/udp
  echo "    ufw rules added. IMPORTANT: if this VPS is behind provider NAT,"
  echo "    opening ufw is NOT enough — you must ALSO forward inbound 3478,"
  echo "    5349 and 49152-49251/udp to this VM in the provider's firewall /"
  echo "    1:1-NAT panel, or clients only ever get STUN (no relay)."
else
  echo "    ufw not present — open 3478 tcp+udp, 5349 tcp+udp, 49152-49251 udp manually"
fi

echo "==> Enabling + starting coturn…"
systemctl enable coturn
systemctl restart coturn
sleep 1
systemctl --no-pager --full status coturn | head -n 15 || true

echo "==> Generating a throwaway 1-hour test credential…"
TEST_USER=$(( $(date +%s) + 3600 ))
TEST_CRED=$(printf '%s' "${TEST_USER}" | openssl dgst -binary -sha1 -hmac "${TURN_SECRET}" | openssl base64)

cat <<DONE

Done.

Verify TURN relay works:
  1) https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
  2) Add server:  turn:${TURN_DOMAIN}:3478
       username:   ${TEST_USER}
       credential: ${TEST_CRED}
     (throwaway cred, valid ~1h — the app mints its own at call time)
  3) "Gather candidates" → you want a candidate of type "relay".
     No relay? Check:  journalctl -u coturn -f
     and confirm the A record is DNS-only (grey cloud) in Cloudflare.

Then deploy the credential function from your dev machine:
  supabase secrets set TURN_SECRET="<the SAME value as TURN_SECRET in this script>"
  supabase functions deploy turn-credentials
DONE
